apiVersion: v1
kind: Service
metadata:
  name: myapp-test
  labels:
    app: myapp-svc
spec:
  # Service 类型，从 values.yaml 文件取
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} # Service 端口，从 values.yaml 文件取
      targetPort: 80
      protocol: TCP
      name: 80-80
      nodePort: 30003
  selector:
    app: myapp-test