apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-deploy-demo # 关联的Deployment名称
  minReplicas: 2 # 最小副本数量
  maxReplicas: 10 # 最大副本数量
  metrics:
    - type: Resource # 指标类型为资源指标
      resource:
        name: cpu # 资源指标名称为CPU
        target:
          type: Utilization # 指标类型为利用率
          averageUtilization: 50 # 目标利用率为50%