apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: emptydir-deployment
  labels:
    name: volumn-dep
spec:
  replicas: 1
  selector:
    matchLabels: # Deployment控制器管理具有如下标签的Pod
      type: emptydir
  template:
    metadata:
      labels: # Pod模板设定生成的Pod有这些标签项
        app: myapp
        type: emptydir
    spec:
      containers:
        - name: nginx-container # Pod1，nginx
          image: wangyanglinux/myapp:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts: # 设置 pod 挂载的容器卷
            - name: log-volume
              mountPath: /usr/local/nginx/logs # 镜像日志输出目录，必须存在
        - name: busybox-container # Pod2，busybox
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          volumeMounts: # 设置 pod 挂载的容器卷
            - name: log-volume
              mountPath: /logs
          command:
            - '/bin/sh'
            - '-c'
            - 'tail -f /logs/access.log'
      volumes:
        - name: log-volume # 设置自定义容器卷的名称
          emptyDir: {} # 容器卷类型：emptyDir