apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-demo # rs的名字，全局唯一，生成的Pod的名字：replica-set-demo-xxxx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels: # 基于标签匹配
      app: rs-ml-demo # ReplicaSet 将管理带有标签 app=rs-ml-demo 的 Pod
  template:
    metadata:
      namespace: default
      labels: # 为 Pod 设置标签
        app: rs-ml-demo # 给 Pod 打上标签 app=rs-ml-demo，与 selector 中的 matchLabels 对应
    spec:
      containers:
        - name: rs-ml-container
          image: wangyanglinux/myapp:v1.0
          imagePullPolicy: IfNotPresent
          env: # 定义容器的环境变量
            - name: GET_HOSTS_FROM
              value: dns
            - name: George
              value: "30"
          ports:
            - containerPort: 80