apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-tolerations-deploy
  labels:
    app: multitolerations-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-pod
          image: wangyanglinux/myapp:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      tolerations:
        - key: "check-nginx"
          operator: "Equal"
          value: "web"
          effect: "NoSchedule"
        - key: check-redis
          operator: Exists
          effect: NoSchedule