apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels: # 标签选择器，管理具有包含以下标签的Pod
      app: nginx-pod
      release: stable
      svc: clusterip
  template:
    metadata:
      labels: # Pod模板定义标签，需完全包含 spec.selector.matchLabels 定义的标签
        app: nginx-pod
        release: stable
        svc: clusterip
        env: test
    spec:
      containers:
        - name: myapp-container
          image: wangyanglinux/myapp:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe: # 定义就绪探测
            httpGet:
              port: 80
              path: /index.html
            initialDelaySeconds: 1
            periodSeconds: 3