apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: # 标签选择器，管理具有包含以下标签的Pod
      app: nginx-pod
      release: stable
      svc: clusterip
  template:
    metadata:
      labels: # Pod模板定义标签，需完全包含 spec.selector.matchLabels 定义的标签
        app: nginx-pod
        release: stable
        svc: clusterip
        env: test
    spec:
      containers:
        - name: myapp-container
          image: wangyanglinux/myapp:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe: # 定义就绪探测
            httpGet:
              port: 80
              path: /index1.html
            initialDelaySeconds: 1
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-clusterip-service
  namespace: default
spec:
  clusterIP: 10.96.120.10 # 手动指定Service的Ip地址，不指定默认自动生成
  type: ClusterIP # Service类型，默认为 ClusterIp，集群内部访问
  selector:
    app: nginx-pod
    release: stable
    svc: clusterip
  ports:
    - name: http
      port: 80 # Service对外暴露的端口
      targetPort: 80 # 转发到Pod的端口
  publishNotReadyAddresses: true # 允许未就绪的 Pod 添加到 Endpoints 中