apiVersion: v1
kind: Pod
metadata:
  name: readiness-exec-pod
  namespace: default
  labels:
    app: myapp
    env: test
spec:
  containers:
    - name: readiness-exec-container
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent # 镜像拉取策略，如果存在则不拉取
      # 主容器启动成功后自动创建目录 /tmp/live, 60秒后删除该目录，
      command: ['/bin/sh', '-c', 'touch /tmp/live; sleep 30; rm -rf /tmp/live; sleep 3600']
      livenessProbe:
        exec:
          command:
            - 'test'
            - '-e'
            - '/tmp/live'
        initialDelaySeconds: 2
        periodSeconds: 3