apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixed-deploy-ip
  labels:
    app: my-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fixed-deploy
  template:
    metadata:
      labels:
        app: fixed-deploy
      annotations:
        # 设置Pod固定ip地址
        "cni.projectcalico.org/ipAddrs": "[\"171.20.42.65\"]"
    spec:
      containers:
        - image: nginx:1.29.0
          imagePullPolicy: IfNotPresent
          name: nginx