apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-demo-pvc
  namespace: default
spec:
  storageClassName: nfs-client # 指定存储类
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-demo
  template:
    metadata:
      labels:
        app: velero-demo
    spec:
      containers:
      - name: velero-demo
        image: nginx:1.29.0
        ports:
        - containerPort: 80
        volumeMounts: # 挂载卷
          - name: velero-storage
            mountPath: /usr/share/nginx/html # 挂载路径
      volumes:
        - name: velero-storage
          persistentVolumeClaim: # 挂载PVC
            claimName: velero-demo-pvc