apiVersion: v1
kind: Secret # 资源类型 Secret
metadata:
  name: mysecret # 自定义 Secret 名称
type: Opaque # Secret类型指定为 Opaque
data:
  password: YWJjMTIzNDU2 # base64 编码后的密码
  username: YWRtaW4= # base64编码后的用户名
immutable: true