apiVersion: v1
kind: Secret # 资源类型 Secret
metadata:
  name: mysecret # 自定义 Secret 名称
type: Opaque # Secret类型指定为 Opaque
data:
  password: YWJjMTIzNDU2 # base64 编码后的密码
  username: YWRtaW4= # base64编码后的用户名

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-opaque-env
spec:
  restartPolicy: Never
  containers:
    - name: myapp
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      env:
        - name: SECRET_USERNAME # 环境变量Key
          valueFrom:
            secretKeyRef:
              key: username # Secret中定义的key
              name: mysecret # Secret名称
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysecret