apiVersion: v1
kind: Secret # 资源类型 Secret
metadata:
  name: mysecret # 自定义 Secret 名称
type: Opaque # Secret类型指定为 Opaque
data:
  password: YWJjMTIzNDU2 # base64 编码后的密码
  username: YWRtaW4= # base64编码后的用户名

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-opaque-env
spec:
  restartPolicy: Never
  containers:
    - name: myapp
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/secret # 挂载到容器内的目录
          name: secret-volume # 挂载的 volume 名称
          readOnly: true # 设置容器 /etc/secret 只读
  volumes:
    - name: secret-volume # 生成的挂在卷名称
      secret: # 挂载 Secret
        secretName: mysecret # Secret名称