apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: k8s-master01 # 选择 Pod 运行的节点的名字
      hostNetwork: true # 主机共享网络
      containers:
        - name: nginx
          image: nginx:1.29.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80