apiVersion: v1
kind: Pod
metadata:
  name: dapi-pod-volume
  namespace: default
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    env: test
  annotations:
    build: two
    builder: George
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: [ 'sh', '-c' ] # 容器启动后，每 10秒打印一次环境变量
      args:
        - while true; do
            if [[ -e /etc/podinfo/labels ]]; then
              echo -en '\n\n'; cat /etc/podinfo/labels; fi;
            if [[ -e /etc/podinfo/annotations ]]; then
              echo -en '\n\n'; cat /etc/podinfo/annotations; fi;
            sleep 5;
          done;
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations