apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo1
spec:
  capacity:
    storage: 5Gi # PV的容量大小 5G
  volumeMode: Filesystem
  accessModes: # PV 访问模式
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete # 回收策略
  storageClassName: slow
  mountOptions:
    - hard # 指定挂载选项为 hard，表示 NFS 挂载是硬挂载，客户端会在连接中断时不断重试。
    - nfsvers=4.1 # 指定使用 NFS 协议版本 4.1。
  nfs:
    path: /root/data/nfs/
    server: 192.168.142.199