apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs1
spec:
  capacity:
    storage: 1Gi # 1G磁盘容量
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # 自动回收的策略
  storageClassName: nfs # 使用NFS
  nfs:
    path: /root/data/nfs1
    server: 192.168.142.199

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs2
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # 自动回收的策略
  storageClassName: nfs # 使用NFS
  nfs:
    path: /root/data/nfs2
    server: 192.168.142.199

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # 自动回收的策略
  storageClassName: nfs # 使用NFS
  nfs:
    path: /root/data/nfs3
    server: 192.168.142.199

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs4
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # 自动回收的策略
  storageClassName: nfs # 使用NFS
  nfs:
    path: /root/data/nfs4
    server: 192.168.142.199

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs5
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle # 自动回收的策略
  storageClassName: nfs # 使用NFS
  nfs:
    path: /root/data/nfs5
    server: 192.168.142.199

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs6
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # 自动回收的策略
  storageClassName: nfs # 使用NFS
  nfs:
    path: /root/data/nfs6
    server: 192.168.142.199