apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-nodeselector-deploy
  labels:
    app: nodeselector-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-pod
          image: wangyanglinux/myapp:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      # 指定节点标签的 key: value
      nodeSelector:
        disk-type: abc