apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-4
  namespace: default
data:
  # 类文件键，每个键都对应一个文件，| 下是文件的内容
  user.properties: |
    age=23
    address=中国
  game.propertie: |
    enemy.types=aliens,monsters
    player.maximum-lives=5

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-5
  namespace: default
data:
  # 类属性键，每个键都映射一个简单的值
  username: "george"
  password: "123456"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-volumn
  namespace: default
spec:
  restartPolicy: Never # Pod 重启策略
  containers:
    - name: myapp-volumn
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      command: # 打印完环境变量后休眠3600秒
        - "/bin/sh"
        - "-c"
        - "env && sleep 3600"
      volumeMounts:
        - name: config-volumn # 挂载的volumn名称，必须在 volumes 有定义
          mountPath: /etc/config
        - name: volumn2
          mountPath: /etc/mydir # 挂载路径不能重复
  volumes:
    - name: config-volumn # volumn 名称
      configMap:
        name: configmap-4 # ConfigMap 名称
    - name: volumn2
      configMap:
        name: configmap-5